# Generated by Django 4.2.10 on 2025-12-18 11:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0003_landlordapplication'),
    ]

    def migrate_estate_data(apps, schema_editor):
        """Copy existing estate string values to estate_name before converting to FK"""
        Property = apps.get_model('properties', 'Property')
        for prop in Property.objects.all():
            if prop.estate and not prop.estate_name:
                # estate is still a CharField at this point
                prop.estate_name = str(prop.estate)
                prop.save()

    operations = [
        # First, add estate_name field and copy data
        migrations.AddField(
            model_name='property',
            name='estate_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(migrate_estate_data, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at', '-featured'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='assigned_caretaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caretaker_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='available_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cleaning_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='estate_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_best_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_multi_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('airbnb', 'Airbnb'), ('commercial', 'Commercial'), ('land', 'Land'), ('sale', 'For Sale')], default='rental', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='location_pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='locations.locationpin'),
        ),
        migrations.AddField(
            model_name='property',
            name='maximum_guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='min_photos_required',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='property',
            name='min_video_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='minimum_nights',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='nightly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='square_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        # First make estate nullable (still CharField)
        migrations.AlterField(
            model_name='property',
            name='estate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # Clear existing estate string values
        migrations.RunSQL(
            "UPDATE properties_property SET estate = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Now convert to ForeignKey
        migrations.AlterField(
            model_name='property',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='locations.estate'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('bedsitter', 'Bedsitter'), ('townhouse', 'Townhouse'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('commercial_building', 'Commercial Building'), ('office_space', 'Office Space'), ('shop', 'Shop'), ('warehouse', 'Warehouse'), ('plot', 'Plot'), ('farm', 'Farm')], default='apartment', max_length=30),
        ),
        migrations.AlterField(
            model_name='propertyamenity',
            name='amenity_type',
            field=models.CharField(choices=[('parking', 'Parking'), ('security', '24/7 Security'), ('water', 'Water Supply'), ('wifi', 'WiFi'), ('gym', 'Gym'), ('pool', 'Swimming Pool'), ('elevator', 'Elevator'), ('balcony', 'Balcony'), ('garden', 'Garden'), ('terrace', 'Terrace'), ('fireplace', 'Fireplace'), ('air_conditioning', 'Air Conditioning'), ('heating', 'Heating'), ('dishwasher', 'Dishwasher'), ('washing_machine', 'Washing Machine'), ('dryer', 'Dryer'), ('tv', 'TV'), ('cable_tv', 'Cable TV'), ('internet', 'Internet'), ('furnished', 'Furnished'), ('semi_furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished'), ('pet_friendly', 'Pet Friendly'), ('smoking_allowed', 'Smoking Allowed'), ('wheelchair_accessible', 'Wheelchair Accessible'), ('near_transport', 'Near Public Transport'), ('near_schools', 'Near Schools'), ('near_hospitals', 'Near Hospitals'), ('near_shopping', 'Near Shopping')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['listing_type', 'available'], name='properties__listing_88fb57_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['verification_status'], name='properties__verific_060ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['estate'], name='properties__estate__4ce096_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude', 'longitude'], name='properties__latitud_6eb2b0_idx'),
        ),
    ]
