# Generated by Django 4.2.10 on 2025-12-18 11:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_landlordapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaretakerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('responsibilities', models.JSONField(default=list, help_text="List of responsibilities, e.g., ['maintenance', 'security', 'cleaning']")),
                ('issues_resolved', models.IntegerField(default=0)),
                ('average_response_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_assignments', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_assignments', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC / Heating'), ('appliances', 'Appliances'), ('structural', 'Structural'), ('pest_control', 'Pest Control'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='reported', max_length=20)),
                ('unit_number', models.CharField(blank=True, max_length=50)),
                ('location_description', models.CharField(blank=True, max_length=200)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Caretaker or maintenance staff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_issues', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_issues', to='properties.property')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('status_change', models.CharField(blank=True, max_length=20)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='maintenance.maintenanceissue')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('inspection_type', models.CharField(choices=[('move_in', 'Move-In Inspection'), ('move_out', 'Move-Out Inspection'), ('routine', 'Routine Inspection'), ('maintenance', 'Maintenance Inspection'), ('safety', 'Safety Inspection')], default='routine', max_length=20)),
                ('checklist', models.JSONField(default=dict, help_text="Checklist items with status, e.g., {'walls': 'good', 'plumbing': 'needs_repair'}")),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('inspector_signature', models.TextField(blank=True)),
                ('tenant_signature', models.TextField(blank=True)),
                ('landlord_signature', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='properties.property')),
            ],
            options={
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='CaretakerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('check_in_location', models.CharField(blank=True, max_length=200)),
                ('check_out_location', models.CharField(blank=True, max_length=200)),
                ('check_in_photo', models.ImageField(blank=True, null=True, upload_to='caretaker/attendance/')),
                ('check_out_photo', models.ImageField(blank=True, null=True, upload_to='caretaker/attendance/')),
                ('tasks_completed', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='maintenance.caretakerassignment')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceissue',
            index=models.Index(fields=['property', 'status'], name='maintenance_propert_30da5b_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceissue',
            index=models.Index(fields=['reported_by', 'status'], name='maintenance_reporte_97c8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceissue',
            index=models.Index(fields=['assigned_to', 'status'], name='maintenance_assigne_5dd113_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceissue',
            index=models.Index(fields=['priority', 'status'], name='maintenance_priorit_e11e0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caretakerattendance',
            unique_together={('assignment', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='caretakerassignment',
            unique_together={('property', 'caretaker')},
        ),
    ]
