# Generated by Django 4.2.10 on 2025-12-18 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('agent', 'Agent'), ('caretaker', 'Caretaker'), ('airbnb_host', 'Airbnb Host'), ('airbnb_guest', 'Airbnb Guest'), ('property_buyer', 'Property Buyer'), ('property_seller', 'Property Seller'), ('developer', 'Developer'), ('lawyer', 'Lawyer / Mortgage Officer'), ('admin', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_switched_at', models.DateTimeField(auto_now=True)),
                ('current_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.userrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_role_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Session',
                'verbose_name_plural': 'Role Sessions',
            },
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role_type'], name='roles_userr_user_id_7b0d11_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='roles_userr_user_id_d3c927_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role_type')},
        ),
    ]
