# Generated by Django 4.2.10 on 2025-12-18 11:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_landlordapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_type', models.CharField(choices=[('residential', 'Residential Lease'), ('commercial', 'Commercial Lease'), ('short_term', 'Short-Term Lease'), ('month_to_month', 'Month-to-Month')], default='residential', max_length=20)),
                ('lease_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('terms', models.TextField(help_text='Lease terms and conditions')),
                ('special_clauses', models.TextField(blank=True)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('renewal_notice_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('landlord_signed', models.BooleanField(default=False)),
                ('tenant_signed', models.BooleanField(default=False)),
                ('landlord_signature', models.TextField(blank=True)),
                ('tenant_signature', models.TextField(blank=True)),
                ('landlord_signed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_document', models.FileField(blank=True, null=True, upload_to='leases/documents/')),
                ('lease_pdf', models.FileField(blank=True, null=True, upload_to='leases/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('landlord', models.ForeignKey(help_text='Property owner/landlord', on_delete=django.db.models.deletion.CASCADE, related_name='landlord_leases', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_leases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('expiry', 'Lease Expiry'), ('renewal', 'Renewal Notice'), ('rent_due', 'Rent Due'), ('inspection', 'Inspection Due'), ('custom', 'Custom')], max_length=20)),
                ('reminder_date', models.DateField()),
                ('message', models.TextField()),
                ('sent_to_landlord', models.BooleanField(default=False)),
                ('sent_to_tenant', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='leases.lease')),
            ],
            options={
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaseAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_type', models.CharField(choices=[('rent_change', 'Rent Change'), ('term_extension', 'Term Extension'), ('term_reduction', 'Term Reduction'), ('add_tenant', 'Add Tenant'), ('remove_tenant', 'Remove Tenant'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('effective_date', models.DateField()),
                ('landlord_signed', models.BooleanField(default=False)),
                ('tenant_signed', models.BooleanField(default=False)),
                ('landlord_signature', models.TextField(blank=True)),
                ('tenant_signature', models.TextField(blank=True)),
                ('amendment_document', models.FileField(blank=True, null=True, upload_to='leases/amendments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='leases.lease')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('lease', 'Lease Agreement'), ('title_deed', 'Title Deed'), ('id', 'ID Document'), ('kra_pin', 'KRA PIN Certificate'), ('utility_bill', 'Utility Bill'), ('inspection_report', 'Inspection Report'), ('maintenance_report', 'Maintenance Report'), ('receipt', 'Receipt'), ('invoice', 'Invoice'), ('contract', 'Contract'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_file', models.FileField(upload_to='documents/vault/')),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('access_level', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leases.lease')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['property', 'status'], name='leases_leas_propert_783306_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['landlord', 'status'], name='leases_leas_landlor_145517_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['tenant', 'status'], name='leases_leas_tenant__9c2189_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['start_date', 'end_date'], name='leases_leas_start_d_b1d1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentvault',
            index=models.Index(fields=['uploaded_by', 'document_type'], name='leases_docu_uploade_d8c9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='documentvault',
            index=models.Index(fields=['property', 'document_type'], name='leases_docu_propert_dea8b9_idx'),
        ),
    ]
