# Generated by Django 4.2.10 on 2025-12-18 11:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_landlordapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('advance_booking_days', models.IntegerField(default=30)),
                ('minimum_booking_days', models.IntegerField(default=1)),
                ('maximum_booking_days', models.IntegerField(blank=True, null=True)),
                ('blocked_dates', models.JSONField(blank=True, default=list)),
                ('available_time_slots', models.JSONField(blank=True, default=list, help_text="List of available time slots, e.g., ['09:00', '10:00', '14:00', '15:00']")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_calendar', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Booking Calendars',
            },
        ),
        migrations.CreateModel(
            name='ViewingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewing_type', models.CharField(choices=[('physical', 'Physical Viewing'), ('virtual', 'Virtual Viewing')], default='physical', max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('alternative_date', models.DateField(blank=True, null=True)),
                ('alternative_time', models.TimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_updates', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('confirmed_time', models.TimeField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('virtual_meeting_link', models.URLField(blank=True)),
                ('virtual_meeting_platform', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('whatsapp', 'WhatsApp Video'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_bookings', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'preferred_date'], name='bookings_vi_propert_532cfb_idx'), models.Index(fields=['user', 'status'], name='bookings_vi_user_id_fef29c_idx'), models.Index(fields=['status', 'preferred_date'], name='bookings_vi_status_5eb60c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AirbnbBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_nights', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('actual_check_in', models.DateTimeField(blank=True, null=True)),
                ('actual_check_out', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_policy', models.CharField(choices=[('flexible', 'Flexible'), ('moderate', 'Moderate'), ('strict', 'Strict')], default='moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_reservations', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_bookings', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_bookings', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'check_in_date'], name='bookings_ai_propert_ee9b1b_idx'), models.Index(fields=['guest', 'status'], name='bookings_ai_guest_i_21e1e8_idx'), models.Index(fields=['host', 'status'], name='bookings_ai_host_id_a9be5b_idx'), models.Index(fields=['status', 'check_in_date'], name='bookings_ai_status_32c1e6_idx')],
            },
        ),
    ]
