# Generated by Django 4.2.10 on 2025-12-18 13:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('id_verified', 'ID Verified'), ('kra_verified', 'KRA PIN Verified'), ('face_verified', 'Face Match Verified'), ('title_deed_verified', 'Title Deed Verified'), ('landlord_verified', 'Verified Landlord'), ('agent_certified', 'Certified Agent'), ('premium_member', 'Premium Member')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'badge_type')},
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(max_length=20)),
                ('verification_level', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('advanced', 'Advanced'), ('premium', 'Premium')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verification_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('id_document_front', models.FileField(blank=True, null=True, upload_to='kyc/ids/front/')),
                ('id_document_back', models.FileField(blank=True, null=True, upload_to='kyc/ids/back/')),
                ('kra_pin_document', models.FileField(blank=True, null=True, upload_to='kyc/kra/')),
                ('title_deed_document', models.FileField(blank=True, null=True, upload_to='kyc/title_deeds/')),
                ('face_photo', models.ImageField(blank=True, null=True, upload_to='kyc/faces/')),
                ('id_verified', models.BooleanField(default=False)),
                ('id_verification_confidence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kra_pin_verified', models.BooleanField(default=False)),
                ('kra_pin_number', models.CharField(blank=True, max_length=20)),
                ('face_match_verified', models.BooleanField(default=False)),
                ('face_match_confidence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('title_deed_verified', models.BooleanField(default=False)),
                ('title_deed_number', models.CharField(blank=True, max_length=100)),
                ('land_registry_verified', models.BooleanField(default=False)),
                ('ai_verification_result', models.CharField(blank=True, max_length=20)),
                ('fraud_risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'role_type'], name='kyc_kycveri_user_id_381daf_idx'), models.Index(fields=['status'], name='kyc_kycveri_status_df6c85_idx')],
                'unique_together': {('user', 'role_type')},
            },
        ),
    ]
